apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-service
  namespace: videocopilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processing-service
  template:
    metadata:
      labels:
        app: video-processing-service
    spec:
      containers:
        - name: video-processing-service
          image: jaiditya/videocopilot-video-processing:latest
          ports:
            - containerPort: 8000
          env:
            - name: INTELLIGENCE_SERVICE_URL
              value: "http://intelligence-service:8002"
---
apiVersion: v1
kind: Service
metadata:
  name: video-processing-service
  namespace: videocopilot
spec:
  selector:
    app: video-processing-service
  ports:
    - port: 8000
      targetPort: 8000
